import type { Metadata } from "next";
import { Alfa_Slab_One, Inter } from "next/font/google";
import clsx from "clsx";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
export const alfaSlab = Alfa_Slab_One({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Prescoolario",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={clsx(
          inter.className,
          alfaSlab.className,
          "bg-gray-800 h-screen w-screen"
        )}
      >
        {children}
      </body>
    </html>
  );
}
